services:
  app:
    container_name: app-rate-limiter
    depends_on:
      redis:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    command: ["gow", "run", "main.go"]
    stdin_open: true
    tty: true
    environment:
      - REDIS_ADDR=redis:6379 # sobrescreve do .env

  redis:
    image: redis:latest
    container_name: redis-rate-limiter
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=redis123
      - REDIS_PORT=6379
      - REDIS_DATABASES=1
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
